version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=production
      - GITHUB_APP_PEM_PATH=/run/secrets/github_app_pem
    restart: always
    secrets:
      - github_app_pem
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
      - qdrant

  
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile-postgres
    env_file:
      - .env
    volumes:
      - ./db_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: always
    networks:
      - app-network

volumes:
  qdrant_data:
    driver: local

secrets:
  github_app_pem:
    file: ./GITHUB_APP_NIGHTLY.pem
  
networks:
  app-network:
    driver: bridge
