version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=production
      - GITHUB_APP_PEM_PATH=/run/secrets/github_app_pem
    restart: always
    secrets:
      - github_app_pem
  
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"

secrets:
  github_app_pem:
    file: ./GITHUB_APP_NIGHTLY.pem