name: Update Docs on GitHub Pages

on:
  push:
    branches:
      - '61-build-docs-and-host-on-github-pages'
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install packages
        run: |
          cd docs
          npm ci
          npm run build

      - name: Build project
        run: |
          cd docs
          npm run build
      
      - name: Add nojekyll file
        run: |
          cd docs
          touch ./out .nojekyll
      
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs/out
          token: ${{ secrets.DEPLOY_TOKEN }}
